### ISSUE TITLE
Contributors section

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/web#1]
The contributors section should list the following people:

---

## Alex Weissman

Alex is the founder and co-owner of two companies, one that does math tutoring at IU in Bloomington, IN and another company that does math tutoring at UMD in College Park, MD. He is also a PhD student in the School of Informatics and Computing at Indiana University.

## Louis Charette

Louis's a civil engineer who also has a passion for coding. He is one of the main contributors for SimpsonsCity.com and like to share is knowledge by helping other the same way he was helped when he first started coding.

## Jordan Mele

(bio pending)

## Mike Jacobs

Mike's a programmer and IT specialist for a small business in NH, and works on open source projects when he's not camping or traveling.

## Srinivas Nukala

(bio pending)

---

We should also have headshots for anyone who wants them, otherwise we can use an avatar.

**Comment by lcharette** [comment]
> We should also have headshots for anyone who wants them, otherwise we can use an avatar.

You can use my avatar.

**Comment by alexweissman** [comment]
yeah, just PM it to @SarahBaghdadi, please.

**Comment by ssnukala** [comment]
Srinivas's a web applications architect, with a passion for open source technologies. He is experienced in building "as a service" web applications and enjoys working on open source projects and contributing to the community. He has a Masters in Computer Science from Pune University, India.

**Comment by ssnukala** [comment]
@SarahBaghdadi 
![ssnukala](https://cloud.githubusercontent.com/assets/5246509/22042910/c8892a00-dcd2-11e6-84f5-cc58f20294a9.jpg)

**Comment by Silic0nS0ldier** [comment]
Jordan’s a developer at Mayvin Training and a student studying Computer Science at the University of Wollongong. His passion is creating software based solutions to overcomplicated problems, without taking control away from the user. He’s also Australian.

---
Also, could you remove `David` from the start of my name? While technically correct, it'll just add a layer or complication that I frankly don't want to have to deal with. Future me will be thankful for this.

**Comment by Silic0nS0ldier** [comment]
@SarahBaghdadi 
![img_t9alfj](https://cloud.githubusercontent.com/assets/17376090/22043378/7fc944c6-dd63-11e6-8be1-4bc6255c7065.jpg)

**Comment by SarahBaghdadi** [comment]
Thanks for posting, I've got all of these loaded. For Mike, I'll use a generic github avatar for now.

**Comment by Netrilix** [comment]
You can use the one attached to my github username for now, I'll try to come up with something better soon.

**Comment by SarahBaghdadi** [comment]
Ok sounds good.
