### ISSUE TITLE
Mobile syles to do

### ISSUE THREAD

**Issue by SarahBaghdadi** [userfrosting/web#10]
For iphone 4 size:
- Footer columns: Align both left. 
- Footer: Hide donate via bitcoin?
- Footer copyright bar: text should wrap to two lines
- Font page "Chance are.." paragraph: padding R & L 0px
- Github button: Padding-top 6px
- Features section title: padding-bottom less
- "See our full list of features" button: text smaller
- Builtwith slider buttons: hide or move

**Comment by SarahBaghdadi** [comment]
Add home link to mobile sidenav

**Comment by SarahBaghdadi** [comment]
Still to do-  Builtwith slider buttons: hide or move

**Comment by alexweissman** [comment]
![screen shot 2017-02-13 at 18 41 58](https://cloud.githubusercontent.com/assets/5004534/22908396/38965b2a-f21c-11e6-83e8-2572eb3db977.png)

Could use some padding on the left and right of the laptop image.  Also, in mobile, the three buttons should all be full-width and stacked.
