### ISSUE TITLE
New sites for "built with userfrosting" gallery

### ISSUE THREAD

**Issue by SarahBaghdadi** [userfrosting/web#18]

**Comment by alexweissman** [comment]
We can try to solicit these when we do the UF survey.  Also, I stumbled across this last night: http://uchi-con.com/

**Comment by SarahBaghdadi** [comment]
potentially some of these...
But at some point we should send an email out.

https://www.shiptsg.com/index.php
http://uchi-con.com/
https://usorgames.com/

**Comment by alexweissman** [comment]
Serious email...  We should add them!
