### ISSUE TITLE
Screenshots needed for "user features" section

### ISSUE THREAD

**Issue by SarahBaghdadi** [userfrosting/web#4]
###  Instructions for screenshots

- Using Firefox, change inspector to mobile view, and resize viewport to 980 x 980 square. 
- Use the built-on screen capture tool to get perfect edges and sizing.

 ### Prep work
- Populate the database with usernames and user activity as needed.

 ### Shot list
- User login
- Permissions & Groups
- Manage Users
- Site Settings
- User dashboard

**Comment by alexweissman** [comment]
Done!  I created some new sections, and removed some of the outdated ones.
